### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by gebeto** [chartjs/Chart.LinearGauge.js#11]
Please select `master` branch for `GitHub Pages` in settings of repository to live preview example.html and add link to description. It will be https://chartjs.github.io/Chart.LinearGauge.js/example
after enabling it in settings

### >>>
![screen shot 2018-11-24 at 9 13 32 pm](https://user-images.githubusercontent.com/13422799/48972169-d30f7400-f02d-11e8-9680-696ea8c214e3.png)

**Comment by simonbrunel** [comment]
Done! Feel free to submit a PR adding a link to that page from the `README.md`.

**Comment by gebeto** [comment]
Thank you! Okay 😄

But I mean to add link to the top of the repo in description section
![screen shot 2018-11-24 at 9 44 23 pm](https://user-images.githubusercontent.com/13422799/48972408-34d1dd00-f032-11e8-923c-05e7c1b0800b.png)

**Comment by simonbrunel** [comment]
Sorry, I didn't read carefully your message :) done!

**Comment by gebeto** [comment]
Thanks!
